image: "pdxfinder/mvn_cd"

stages:
  - setup
  - build
  - deploy

setup:
  cat << EOF > settings.xml
  <settings>
  <servers>
  <server>
  <id>ossrh</id>
  <username>$OSSRH_use</username>>
  <password>\$OSSRH_pass</password>
  </server>
  </servers>
  <profiles>
  <profile>
  <id>ossrh</id>
  <activation>
  <activeByDefault>true</activeByDefault>
  </activation>
  <properties>
  <gpg.executable>gpg2</gpg.executable>
  <gpg.keyname></gpg.keyname>
  <gpg.passphrase>key_passphrase</gpg.passphrase>
  </properties>
  </profile>
  </profiles>
  </settings>
  EOF
  gpg2 --import $pk_base64


build:
  echo 'Building'


deploy:
  echo 'Deploying'