language: java
sudo: false
jdk:
  - openjdk11
env:
  global:
    - JAVA_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmn48M -Xmx512M"
    - NUM_THREADS=2
    - NODE_VERSION="8.11.3"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/969b5598af30afd3e0a2
    on_success: always
    on_failure: always
    on_start: never
addons:
  sonarcloud:
    organization: pdxfinder
    token:
      secure: "P/vA68w0+FDqgDlcgdr0nr2wJCwCkUwjxnqzqNNtMao+DqHIXsE59VhlJdCY7i0XdCF1deAjXujXTpdHUDHJ5/nLJ7PQ71vu5WQ0wCv9bXCm3Wu6z0Da8vNRtFuKpBFHTjpwo/99M2HxyVQG21YZzjqecWSKecICN3kFx1YNjIngwzjeN2Oi3bpqmm4z0ZnyVlvpRNWNXTuiGACotCashH7ClOfDVIOT7h9Op8BfnAgVL8WCymn4KhI9SUhAo1TuCCZXWJCo12sSxeUhzDTUDBC/Ea+9ud3LvYsn8Kav3RyeYOe8q0YBNEEYKrfWiNVynhT5K6UiQ95XLW8Esc4EgYVspW1GRBACk7b/wSUwvSNeLoSoz4cAVy/l6tKII9HOYRAbyyQ/0CzjYkxP7cy3jiNsedq7+WlOYlGRwQkM/P/QL2nfKwE/7fka62WakI1ktIEys2mBq6cfgiVQNbiJ/vRa5AShsDCVkejoj2jhF5RSjHwYTqdQkOPHWKbRhYhLRjqBoIrh7lYQlCl83UD/S9ZpSveDk8AjXVTG0wY9xTDBmM6qwlok4Lmf1C02gh/HBdXNPn5gGvZ90qj9lXyYNDhdGcpPjqkwH/BoXGNBtc6kGxOzl9xE2KZqARiclfOQ8+TXmWlLZtg6mGrrwCWSvF3V3JUBIPyeg3qpX4iQSas="
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=data-model